### ISSUE TITLE
Python24 > 04 : Built In Functions That using math 

### ISSUE THREAD

**Issue by hammad-ibrahim** [DevOps-With-Hammad/Software_enginnering-Code_base#15]
**As a** [Python Programmer ]  
 **I need** [To declare 3 Vars  with assigned values ]  
 **So that** [So  that I can apply the the function (min, max, avg) on these Vars ]  
   
 ### Details and Assumptions
 * [Exercise 4.1 built in Functions that Use Math
"""
Isuzu is 1.70 Million market share.
Toyota is 2.3 Million market share.
Suzuki is 0.9 Million market share.

01- Create the Variables of market share for each brand
02- The average height is [Put the average height here ].
03- the maximum market share [put here ] also the minimum market share .]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [certain action is taken]
 Then [the outcome of action is observed]
 ```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Created a new file '6. [BIA] Exercise 4.1 Built-in Functions Using Math.py' to implement the requested functionality for calculating market share statistics of car brands.

You can review changes in this commit: https://github.com/mnmnk43434/DevOps-With-Hammad-Software_enginnering-Code_base-15/commit/a6cbead7e480a72beab4f5ddb431cb4f790b9368.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
